language: node_js
node_js:
- '0.10'
sauce_connect: true
before_install: npm install -g karma-cli
before_script: npm install karma-sauce-launcher
script: karma start karma.conf-sauce.js
env:
    global:
    - NPM_CONFIG_PROGRESS="false"
cache:
    directories:
    - node_modules
